### ISSUE TITLE
Xbox Store?

### ISSUE THREAD

**Issue by JeffreyLynch** [Lyall/SMTVFix#3] opened 2024-06-14 22:53 UTC
This doesn't seem to work for the Xbox Store version.
The Persona 3 Reload ultrawidescreen fix did.

**Comment by SpaceGoat04** [comment] 2024-06-14 23:38
The problem seems to be with the developer console, setting it to disabled will let the game boot.
That being said the intro skip flag doesn't seem to work, can't say anything about ultrawide fixes since I don't have a monitor of that aspect ratio.
TAA does work by the way, so it seems this is at least doing something with this version of the game.

Full log:

[2024-06-14 20:32:27.369] [SMTVFix] [info] ----------
[2024-06-14 20:32:27.369] [SMTVFix] [info] SMTVFix v0.8.2 loaded.
[2024-06-14 20:32:27.369] [SMTVFix] [info] ----------
[2024-06-14 20:32:27.369] [SMTVFix] [info] Path to logfile: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK\SMTVFix.log
[2024-06-14 20:32:27.369] [SMTVFix] [info] ----------
[2024-06-14 20:32:27.369] [SMTVFix] [info] Module Name: SMT5V-WinGDK-Shipping.exe
[2024-06-14 20:32:27.369] [SMTVFix] [info] Module Path: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK\
[2024-06-14 20:32:27.369] [SMTVFix] [info] Module Address: 0x140000000
[2024-06-14 20:32:27.369] [SMTVFix] [info] Module Timestamp: 1713418627
[2024-06-14 20:32:27.369] [SMTVFix] [info] ----------
[2024-06-14 20:32:27.374] [SMTVFix] [info] Path to config file: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK\SMTVFix.ini
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bIntroSkip: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bEnableConsole: false
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bDisableMenuFPSCap: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixAspect: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixHUD: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixFOV: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bScreenPercentage: false
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: fScreenPercentage: 100
[2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bEnableTAA: true
[2024-06-14 20:32:27.374] [SMTVFix] [info] ----------
[2024-06-14 20:32:27.800] [SMTVFix] [error] Current Resolution: Pattern scan failed.
[2024-06-14 20:32:27.832] [SMTVFix] [info] Aspect Ratio/FOV: Address is SMT5V-WinGDK-Shipping.exe+2020e28
[2024-06-14 20:32:27.868] [SMTVFix] [info] HUD: HUD Position: Address is SMT5V-WinGDK-Shipping.exe+1cdcb24
[2024-06-14 20:32:27.913] [SMTVFix] [info] HUD: Markers: Address is SMT5V-WinGDK-Shipping.exe+2430938
[2024-06-14 20:32:28.018] [SMTVFix] [info] CVARS: Anti Aliasing CVAR: Address is SMT5V-WinGDK-Shipping.exe+43ca1c8
[2024-06-14 20:32:28.018] [SMTVFix] [info] CVARS: Half Res AO CVAR: Address is SMT5V-WinGDK-Shipping.exe+42d3060
[2024-06-14 20:32:28.060] [SMTVFix] [info] Screen Percentage: Address is SMT5V-WinGDK-Shipping.exe+226980c
[2024-06-14 20:32:28.074] [SMTVFix] [info] Menu Framerate Cap: Address is SMT5V-WinGDK-Shipping.exe+ba4c06

**Comment by JeffreyLynch** [comment] 2024-06-15 01:15
Y

> The problem seems to be with the developer console, setting it to disabled will let the game boot. That being said the intro skip flag doesn't seem to work, can't say anything about ultrawide fixes since I don't have a monitor of that aspect ratio. TAA does work by the way, so it seems this is at least doing something with this version of the game.
> 
> Full log:
> 
> [2024-06-14 20:32:27.369] [SMTVFix] [info] ---------- [2024-06-14 20:32:27.369] [SMTVFix] [info] SMTVFix v0.8.2 loaded. [2024-06-14 20:32:27.369] [SMTVFix] [info] ---------- [2024-06-14 20:32:27.369] [SMTVFix] [info] Path to logfile: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK\SMTVFix.log [2024-06-14 20:32:27.369] [SMTVFix] [info] ---------- [2024-06-14 20:32:27.369] [SMTVFix] [info] Module Name: SMT5V-WinGDK-Shipping.exe [2024-06-14 20:32:27.369] [SMTVFix] [info] Module Path: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK [2024-06-14 20:32:27.369] [SMTVFix] [info] Module Address: 0x140000000 [2024-06-14 20:32:27.369] [SMTVFix] [info] Module Timestamp: 1713418627 [2024-06-14 20:32:27.369] [SMTVFix] [info] ---------- [2024-06-14 20:32:27.374] [SMTVFix] [info] Path to config file: C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt\Project\Binaries\WinGDK\SMTVFix.ini [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bIntroSkip: true [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bEnableConsole: false [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bDisableMenuFPSCap: true [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixAspect: true [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixHUD: true [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bFixFOV: true [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bScreenPercentage: false [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: fScreenPercentage: 100 [2024-06-14 20:32:27.374] [SMTVFix] [info] Config Parse: bEnableTAA: true [2024-06-14 20:32:27.374] [SMTVFix] [info] ---------- [2024-06-14 20:32:27.800] [SMTVFix] [error] Current Resolution: Pattern scan failed. [2024-06-14 20:32:27.832] [SMTVFix] [info] Aspect Ratio/FOV: Address is SMT5V-WinGDK-Shipping.exe+2020e28 [2024-06-14 20:32:27.868] [SMTVFix] [info] HUD: HUD Position: Address is SMT5V-WinGDK-Shipping.exe+1cdcb24 [2024-06-14 20:32:27.913] [SMTVFix] [info] HUD: Markers: Address is SMT5V-WinGDK-Shipping.exe+2430938 [2024-06-14 20:32:28.018] [SMTVFix] [info] CVARS: Anti Aliasing CVAR: Address is SMT5V-WinGDK-Shipping.exe+43ca1c8 [2024-06-14 20:32:28.018] [SMTVFix] [info] CVARS: Half Res AO CVAR: Address is SMT5V-WinGDK-Shipping.exe+42d3060 [2024-06-14 20:32:28.060] [SMTVFix] [info] Screen Percentage: Address is SMT5V-WinGDK-Shipping.exe+226980c [2024-06-14 20:32:28.074] [SMTVFix] [info] Menu Framerate Cap: Address is SMT5V-WinGDK-Shipping.exe+ba4c06
> 
> Note: "C:\Program Files\WindowsApps\SEGAofAmericaInc.654516CB659FE_1.7.1.0_x64__s751p9cej88mt" seems to be the same than "C:\XboxGames\Shin Megami Tensei V Vengeance\Content".

This log dump actually helped me solve it.  Putting the files in Project\Binaries\WinGDK rather than the default Project\Binaries\Win64 seemed to do the trick!

**Comment by Lyall** [comment] 2024-06-15 13:03
I don't have access to the Xbox store version so the next best thing would be if you can dump the game executable using [UWPDumper](https://github.com/Wunkolo/UWPDumper). Then I could at least compare the patterns on the exe. I can also add a separate release artifact for the Xbox store version too with the WinGDK folder already prepopulated.

**Comment by blueskythlikesclouds** [comment] 2024-06-16 16:47
I'd like to provide the executable. How could I send it to you?

**Comment by Lyall** [comment] 2024-06-16 21:35
Okay thanks to being sent the Xbox Store version I've made some changes that should hopefully make SMTVFix compatible with it. Can you try out this test build? If you do, please post your log file after and let me know if anything doesn't work properly.

[SMTVFix_v0.8.4_Xbox.zip](https://github.com/user-attachments/files/15859913/SMTVFix_v0.8.4_Xbox.zip)

**Comment by blueskythlikesclouds** [comment] 2024-06-16 21:50
[SMTVFix.log](https://github.com/user-attachments/files/15859925/SMTVFix.log)

Intro logo skip doesn't do anything.
Developer console makes the game crash before any of the intro logos show up.

![SMT5V-WinGDK-Shipping_qKwYtZClU9](https://github.com/Lyall/SMTVFix/assets/19259897/80bbfe53-31fb-4454-84cd-5894f2e87d96)

Fix aspect ratio makes the game squished like this.

Rest of the options seem to work.

**Comment by SpaceGoat04** [comment] 2024-06-16 21:53
Not sure if this changes anything, but the intro sequence is slighty different from the Steam release. Just like Persona 3 Reload, a little message shows up before the intro logos confirming which Xbox user is going to play the game.

Got the same results too, the fix aspect ratio flag makes the game squished (at least with a 16:9 monitor). The TAA, TAAU Gen5 and GTAO flags work fine just like the regular build.

**Comment by Lyall** [comment] 2024-06-16 22:04
Hmm it looks any part of the fix that relies on the dumped SDK doesn't work with the Xbox build.

**Comment by blueskythlikesclouds** [comment] 2024-06-16 22:10
Would it help if I made a SDK dump myself and send it to you?

**Comment by Lyall** [comment] 2024-06-16 22:25
> Would it help if I made a SDK dump myself and send it to you? (Take in mind I'm not sure how that goes.)

Possibly, but I doubt it. Assuming the Xbox build runs the same version of UE4 it should be compatible but I'm not in familiar territory here.

Okay I've added more logging and checks to this build. Let me know how this one goes.

[SMTVFix_v0.8.4_Xbox.zip](https://github.com/user-attachments/files/15860007/SMTVFix_v0.8.4_Xbox.zip)

**Comment by blueskythlikesclouds** [comment] 2024-06-16 22:43
[SMTVFix.log](https://github.com/user-attachments/files/15860049/SMTVFix.log)

Developer console option isn't crashing anymore, and the squishing is gone. Intro skip still doesn't work. I'm not sure if the ultrawide options actually do anything though since I have a 16:9 screen.

**Comment by Lyall** [comment] 2024-06-16 23:29
> [SMTVFix.log](https://github.com/user-attachments/files/15860049/SMTVFix.log)
> 
> Developer console option isn't crashing anymore, and the squishing is gone. Intro skip still doesn't work. I'm not sure if the ultrawide options actually do anything though since I have a 16:9 screen.

Hmm, it's definitely failing to find objects that are fetched through the SDK. I'll have to think on it. I'm not if I'll be able to add support for the Xbox store version if it uses a different UE4 version.

**Comment by JeffreyLynch** [comment] 2024-06-17 07:58
> [SMTVFix.log](https://github.com/user-attachments/files/15860049/SMTVFix.log)
> 
> Developer console option isn't crashing anymore, and the squishing is gone. Intro skip still doesn't work. I'm not sure if the ultrawide options actually do anything though since I have a 16:9 screen.

I can confirm that ultrawide works on a 32:9 ultrawide screen.

**Comment by camirock17** [comment] 2024-06-20 00:33
I second this: last one possible from here, is 0.8.4 WDK, but after that, every single one crashes even if you disable stuff from the .ini

**Comment by AprilSparkle** [comment] 2024-06-22 10:49
v0.9.0 also crashes Microsoft version.Tried to use force 4K cutscene...but seems like few support is coming to Microsoft version...Reload-II mod tool failed due to Microsoft version's DRM on .exe and SMTVfix just crash the game.

**Comment by SpaceGoat04** [comment] 2024-06-22 11:35
The force 4K mod can be converted into a regular .pak mod which works just fine with this version of the game, just tried that myself. 

That being said taking a look at the mod file structure and the game file structure, it seems some folders and files are in different locations/are just not there at all, so I can't guarantee converting the mod will work at all times, so far the intro and game over screen work, but I'm not sure about other scenes.

Creating a force 4k cutscene mod is possible for this version though, but it will require taking a look at the file structure of this specific release.

**Comment by AprilSparkle** [comment] 2024-06-22 12:34
> The force 4K mod can be converted into a regular .pak mod which works just fine with this version of the game, just tried that myself.
> 
> That being said taking a look at the mod file structure and the game file structure, it seems some folders and files are in different locations/are just not there at all, so I can't guarantee converting the mod will work at all times, so far the intro and game over screen work, but I'm not sure about other scenes.
> 
> Creating a force 4k cutscene mod is possible for this version though, but it will require taking a look at the file structure of this specific release.

Thank you.I will try .pak mod too.
BTW will it be possible that v1.0 ver SMTVfix works for the Microsoft version?I

**Comment by n0tleinad** [comment] 2024-06-24 03:29
> I don't have access to the Xbox store version so the next best thing would be if you can dump the game executable using [UWPDumper](https://github.com/Wunkolo/UWPDumper). Then I could at least compare the patterns on the exe. I can also add a separate release artifact for the Xbox store version too with the WinGDK folder already prepopulated.

Hi, i would like to try that, since i own the Xbox store version, what exactly do you need about the dumping? im basically going blind to this and following a reddit post on how to use UWPDumper

**Comment by AprilSparkle** [comment] 2024-06-25 15:14
> I don't have access to the Xbox store version so the next best thing would be if you can dump the game executable using [UWPDumper](https://github.com/Wunkolo/UWPDumper). Then I could at least compare the patterns on the exe. I can also add a separate release artifact for the Xbox store version too with the WinGDK folder already prepopulated.

Err i zipped the execution file but the zip pack is 228MB big i can't attach it in this reply.
But i checked the information of the execution file too it says file version number is 4.27.2.0 and product version is <++UE4+Release-4.27-CL-0> i think that should be the version of Unreal Engine which MS port used.

**Comment by Lyall** [comment] 2024-06-26 23:20
Sorry, I should posted that I've already been sent the WinGDK binary by a user already. No need for anyone else to dump the exe. The latest version (v0.9.1) has some changes to possibly improve compatibility with the Xbox/MS Store build. Remember that you'll have to extract the files from `Project\Binaries\Win64` of the zip to `Project\Binaries\WinGDK` in the game folder instead. If someone try this version, can you please post a log file?

**Comment by n0tleinad** [comment] 2024-06-27 01:07
Hi, i would also like to contribute with my Log file, same as the person before me, all works fine by increasing the injection delay
But in my case at least, the game crashes if i try to use the logos and intro skips (still no console enabled) after loading a save file 
Here's my Log with intro and logos skip on, also 10000ms [SMTVFix.log](https://github.com/user-attachments/files/16006413/SMTVFix.log)

**Comment by Luizzhh** [comment] 2024-06-27 02:18
V0.9.1 works for me with the Xbox version, also had to modify the injection delay, in my case, the minimum of 2388 did work, any lower and the game would start. The Xbox version has an additional DRM that does a check before launching the game, and for that it needs an internet connection.

Just like n0tleinad said, the logos and intro skips will crash the game the moment I try to load a save file.
The developer console will crash the game a couple of seconds after launching it.
Also, the [Adjust Player Camera] options doesn't work, tried enabling it and adjusting the numbers but the camera remains the same has the default settings.

Adding the log file with the camera settings enabled
(English is not my main language)
[SMTVFix.log](https://github.com/user-attachments/files/16006991/SMTVFix.log)

**Comment by SpaceGoat04** [comment] 2024-06-27 05:24
I can confirm it does work too, although setting the injection delay to 2388ms still crashed the game, 10000ms did the trick.

Dev console still crashes the game as usual, can't say anything about the ultrawide patches as I don't have a monitor with that aspect ratio. As for the new graphics related flags (GTAO, shadows, LODs and SSGI) they do work as expected, so does the force 4K videos option.

Attaching log file with all settings being used:
[SMTVFix.log](https://github.com/user-attachments/files/16008294/SMTVFix.log)

**Comment by AprilSparkle** [comment] 2024-06-27 11:05
Set at 10000ms open game three times only got one crash at least i got into the game with this fix.Disabled [Enable Console]
 and [Intro Skip],everything works fine,cutscene is 4K too.
The time game crashed,i felt a little FPS drop since i open a lot of graphic tweak function,so i decide to move the game to my M.2 SSD(It was installed in a SATA3 SSD).Then after the first open after game file arrived at M.2 SSD the game crashes but after the second opening game works fine.
Here's the log in case you might need.Thank you for the fix.
[SMTVFix.log](https://github.com/user-attachments/files/16012431/SMTVFix.log)

**Comment by Luizzhh** [comment] 2024-08-13 00:49
Latest working version for the xbox store game is 0.9.2
Both 0.9.3 and 0.9.4 crashes the game as soon as it launches, if I had to guess, the xbox version needs the delay to be able to work.

The attached log file is from 0.9.4
[SMTVFix.log](https://github.com/user-attachments/files/16593097/SMTVFix.log)

In case you didnt know, the xbox version doesnt launch the game as soon as you try to open it, first it does some checks (probably drm)
![Capture](https://github.com/user-attachments/assets/2de83263-2ccc-4327-a2eb-3f6dbf932997)

**Comment by camirock17** [comment] 2024-09-01 14:44
Now it's fixed on 0.9.6 version! :D

**Comment by Lyall** [comment] 2024-09-01 23:17
Thanks to feedback in #48, v0.9.7 has been released and should be Xbox/MS Store compatible.

**Closed by Lyall** 2024-09-01 23:17 UTC
