### ISSUE TITLE
Fix not loading changes after latest update

### ISSUE THREAD

**Issue by KappnKyro** [Lyall/SMTVFix#52] opened 2024-09-07 01:42 UTC
I previously used an outdated version of the fix, and it would no longer boot after updating the game. I updated the fix, and the game now boots, but none of the fix changes are loaded. The intro movie is not skipped, and I can see that the graphical adjustments set in the fix are not changed in the game.

This issue happens on both my Windows PC via Steam and Steam Deck. The fix was working on both systems before the updates (game and fix).

LOG (from PC):
[2024-09-06 10:16:53.304] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.304] [SMTVFix] [info] SMTVFix v0.9.7 loaded.
[2024-09-06 10:16:53.304] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.304] [SMTVFix] [info] Path to logfile: C:\Program Files (x86)\Steam\steamapps\common\SMT5V\Project\Binaries\Win64\SMTVFix.log
[2024-09-06 10:16:53.304] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.304] [SMTVFix] [info] Module Name: SMT5V-Win64-Shipping.exe
[2024-09-06 10:16:53.304] [SMTVFix] [info] Module Path: C:\Program Files (x86)\Steam\steamapps\common\SMT5V\Project\Binaries\Win64\
[2024-09-06 10:16:53.304] [SMTVFix] [info] Module Address: 0x140000000
[2024-09-06 10:16:53.304] [SMTVFix] [info] Module Timestamp: 1722529992
[2024-09-06 10:16:53.304] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.304] [SMTVFix] [info] Path to config file: C:\Program Files (x86)\Steam\steamapps\common\SMT5V\Project\Binaries\Win64\SMTVFix.ini
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bIntroSkip: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bIntroSkipMovie: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bEnableConsole: false
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bDisableMenuFPSCap: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bFixAspect: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bFixHUD: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bFixFOV: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bFixBattleTransition: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bAdjustCam: false
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fAdjustFOV: 60
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fAdjustDist: 580
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fAdjustHeight: 73
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bForceMovieRes: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bPauseOnFocusLoss: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bScreenPercentage: false
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fScreenPercentage: 100
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bEnableTAA: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bEnableGen5TAAU: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bShadowQuality: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: iShadowResolution: 4096
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bAdjustLOD: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fViewDistanceScale: 10
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: fFoliageDistanceScale: 10
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bEnableGTAO: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bGTAOHalfRes: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: iSSAOLevel: 1
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bEnableSSGI: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: iSSGIQuality: 4
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bHalfResSSGI: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bVignette: true
[2024-09-06 10:16:53.305] [SMTVFix] [info] Config Parse: bUROEnabled: false
[2024-09-06 10:16:53.305] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.305] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: Scaled Resolution: 3440x1440
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: Screen Percentage: 100
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: Base Resolution: 3440x1440
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fAspectRatio: 2.3888888
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fAspectMultiplier: 1.34375
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fHUDWidth: 2560
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fHUDHeight: 1440
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fHUDWidthOffset: 440
[2024-09-06 10:16:53.305] [SMTVFix] [info] Current Resolution: fHUDHeightOffset: 0
[2024-09-06 10:16:53.305] [SMTVFix] [info] ----------
[2024-09-06 10:16:53.312] [SMTVFix] [info] Offsets: GObjects: Address is SMT5V-Win64-Shipping.exe+829ace
[2024-09-06 10:16:53.312] [SMTVFix] [info] Offsets: GObjects: Offset: 43f9320
[2024-09-06 10:16:53.326] [SMTVFix] [info] Offsets: AppendString: Address is SMT5V-Win64-Shipping.exe+eba7f0
[2024-09-06 10:16:53.326] [SMTVFix] [info] Offsets: AppendString: Offset: eba7f0
[2024-09-06 10:16:53.338] [SMTVFix] [info] Offsets: ProcessEvent: Address is SMT5V-Win64-Shipping.exe+10b2930
[2024-09-06 10:16:53.338] [SMTVFix] [info] Offsets: ProcessEvent: Offset: 10b2930
[2024-09-06 10:16:53.367] [SMTVFix] [info] Current Resolution: Address is SMT5V-Win64-Shipping.exe+235b797
[2024-09-06 10:16:53.380] [SMTVFix] [info] Console CVARs: Address is SMT5V-Win64-Shipping.exe+d9f800
[2024-09-06 10:16:53.380] [SMTVFix] [info] Console CVARs: IConsoleManager singleton address is SMT5V-Win64-Shipping.exe+4360ed0
[2024-09-06 10:16:53.480] [SMTVFix] [info] Console CVARs: Cached all console objects.
[2024-09-06 10:16:53.730] [SMTVFix] [error] Intro Skip: Pattern scan failed.
[2024-09-06 10:16:53.754] [SMTVFix] [info] FOV: Address is SMT5V-Win64-Shipping.exe+20eea9c
[2024-09-06 10:16:53.781] [SMTVFix] [info] Aspect Ratio: Address is SMT5V-Win64-Shipping.exe+20f90ae
[2024-09-06 10:16:53.811] [SMTVFix] [info] Freecam Aspect Ratio: Address is SMT5V-Win64-Shipping.exe+24e33d1
[2024-09-06 10:16:53.853] [SMTVFix] [info] Render Texture 2D Resolution: Address is SMT5V-Win64-Shipping.exe+2664f10
[2024-09-06 10:16:53.942] [SMTVFix] [info] Movies: Prepare: Address is SMT5V-Win64-Shipping.exe+5ec0120
[2024-09-06 10:16:53.951] [SMTVFix] [info] Movies: Stop: Address is SMT5V-Win64-Shipping.exe+8a9a20
[2024-09-06 10:16:53.988] [SMTVFix] [info] HUD: Markers: Address is SMT5V-Win64-Shipping.exe+25090ce
[2024-09-06 10:16:53.997] [SMTVFix] [info] HUD: HUDBackgrounds: Address is SMT5V-Win64-Shipping.exe+8f6322
[2024-09-06 10:16:54.008] [SMTVFix] [info] HUD: PauseBG: Address is SMT5V-Win64-Shipping.exe+b61d09
[2024-09-06 10:16:54.022] [SMTVFix] [info] HUD: EncountPanelSlot: Address is SMT5V-Win64-Shipping.exe+f6cc4b
[2024-09-06 10:16:54.050] [SMTVFix] [info] HUD: HUD Position: Address is SMT5V-Win64-Shipping.exe+1dbcfba
[2024-09-06 10:16:54.084] [SMTVFix] [info] Set CVARS: Address is SMT5V-Win64-Shipping.exe+23417cc
[2024-09-06 10:16:54.095] [SMTVFix] [info] Menu Framerate Cap: Address is SMT5V-Win64-Shipping.exe+b5ea76
[2024-09-06 10:16:54.105] [SMTVFix] [info] Movie Resolution: Address is SMT5V-Win64-Shipping.exe+a9e02e
[2024-09-06 10:16:54.105] [SMTVFix] [info] Movie Resolution: Patched instruction.
[2024-09-06 10:16:57.048] [SMTVFix] [info] Render Texture 2D Resolution: RT_EncountScene: Old render texture resolution = 1280x720
[2024-09-06 10:16:57.048] [SMTVFix] [info] Render Texture 2D Resolution: RT_EncountScene: New render texture resolution = 3440x1440
[2024-09-06 10:16:57.442] [SMTVFix] [info] Set CVARS: Set r.DefaultFeature.AntiAliasing to 2
[2024-09-06 10:16:57.442] [SMTVFix] [info] Set CVARS: Set r.VertexDeformationOutputsVelocity to 1
[2024-09-06 10:16:57.442] [SMTVFix] [info] Set CVARS: Set r.AmbientOcclusion.HalfRes to 0
[2024-09-06 10:16:57.442] [SMTVFix] [info] Set CVARS: Set r.TemporalAA.Algorithm to 1
[2024-09-06 10:16:57.442] [SMTVFix] [info] Set CVARS: Set r.AmbientOcclusion.Method to 1
[2024-09-06 10:16:57.443] [SMTVFix] [info] Set CVARS: Set r.GTAO.Downsample to 1
[2024-09-06 10:16:57.443] [SMTVFix] [info] Set CVARS: Set foliage.LODDistanceScale to 10
[2024-09-06 10:16:57.443] [SMTVFix] [info] Set CVARS: Set r.ViewDistanceScale to 10
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set r.SkeletalMeshLODBias to -1
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set r.SSGI.Enable to 1
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set r.SSGI.HalfRes to 1
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set a.URO.Enable to 0
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set r.Shadow.MaxCSMResolution to 4096
[2024-09-06 10:16:57.444] [SMTVFix] [info] Set CVARS: Set r.Shadow.MaxResolution to 4096
[2024-09-06 10:16:57.906] [SMTVFix] [info] Set CVARS: Set r.DefaultFeature.AntiAliasing to 2
[2024-09-06 10:16:58.030] [SMTVFix] [info] Intro Skip: Skipped intro logos.
[2024-09-06 10:16:58.599] [SMTVFix] [info] Movies: Prepare: WBP_EventMovie_C address = 66e5e980
[2024-09-06 10:17:01.152] [SMTVFix] [info] Movies: Stop: Movie stopped.

**Comment by Lyall** [comment] 2024-09-07 04:03
The intro movie skip is definitely broken as of the latest game update. I'll need to look at fixing that. As for the graphical options not applying, can you enable the console just to confirm that they aren't? Because your log looks good and there's no obvious error (apart from the intro movie skip failing).

**Comment by KappnKyro** [comment] 2024-09-07 06:25
I enabled the console and bound it to a key, but I'm unsure how to use it to show you what you need. Let me know what I need to do for that.

I jumped the gun, saying it wasn't changing anything because it appropriately adjusts to my Ultrawide monitor and Steam Deck screens. However, along with the intro skip not working, the resolution scaling isn't working either. That's why I assumed nothing was working since I had it scaled down on my Steam Deck and immediately noticed it wasn't scaling anymore. I haven't tested the rest of the graphical options, but from a glance, I think most other settings are applied in-game.

If you'd like a log from my Steam Deck let me know.

**Comment by ALLEN2CE** [comment] 2024-09-07 07:26
Can confirm that the resolution scaling does not work in this update either, for some reason in the log file. If you set resolution scaling to 200, it becomes half of what your native resolution is. If its set to 50, it doubles your native resolution. However ingame the resolution scaling doesnt work despite the log file stating that it does

**Comment by Lyall** [comment] 2024-09-08 17:38
> r.SSGI.Enable

If you just try typing in (for example) `r.SSGI.Enable` (if you have it enabled) to the console and hit enter, it should tell you what value it's set to and what set it. If it's working, it'll say something like set by "commandline".

Based on what you and @ALLEN2CE have said it seems like resolution scaling is broken, likely due to the resolution hook I changed to accommodate the Microsoft Store version. As for the intro movie skip, that's definitely busted. The function that hooked into is no longer used so I'll have to find another way of skipping it.

**Comment by Lyall** [comment] 2024-09-08 19:17
Here is a test build with the latest commits. It should fix the resolution scaling (screen percentage) not applying and being reported correctly. It also fixes the broken intro movie skip.

[SMTVFix_v0.9.8_Steam.zip](https://github.com/user-attachments/files/16923393/SMTVFix_v0.9.8_Steam.zip)

**Comment by KappnKyro** [comment] 2024-09-09 02:48
The intro skip is working, but the resolution scaling is not. I tested this on my PC and Steam Deck, and I didn't see any changes. And regarding the intro skip, it looks like the game now goes through two loading screens on boot before reaching the title screen, while it previously would go straight to the title screen.

**Comment by Lyall** [comment] 2024-09-09 03:04
> The intro skip is working, but the resolution scaling is not. I tested this on my PC and Steam Deck, and I didn't see any changes. And regarding the intro skip, it looks like the game now goes through two loading screens on boot before reaching the title screen, while it previously would go straight to the title screen.

Give this one a try. Should fix the res scaling issue. 

[SMTVFix_v0.9.8_Steam.zip](https://github.com/user-attachments/files/16924931/SMTVFix_v0.9.8_Steam.zip)

**Comment by KappnKyro** [comment] 2024-09-09 03:16
Looks like the resolution scaling is working now too. Thank you so much for working on this with me!

**Comment by Lyall** [comment] 2024-09-09 03:22
> Looks like the resolution scaling is working now too. Thank you so much for working on this with me!

No problem! With that, the issue is resolved in v0.9.8

**Closed by Lyall** 2024-09-09 03:22 UTC
