### ISSUE TITLE
new update killed it

### ISSUE THREAD

**Issue by MyNameMow2** [Lyall/SMTVFix#44] opened 2024-07-12 15:45 UTC
the update that came out on 7/11/24 killed the fix. at first it made the game crash on bootup, but uninstalling and reinstalling the old fix made the game launch, but the fix was dead even if i could get into the game

**Comment by ofsaleem** [comment] 2024-07-12 22:45
![image](https://github.com/user-attachments/assets/bfed0df4-77bc-4e6d-8795-b3b4503d005e)
that's weird, unless i'm misunderstanding steamdb, the 1.0.2 updates to the game aren't live on the public branch yet

**Comment by jacket50b** [comment] 2024-07-15 13:38
I recently had this problem, could not boot up the game, removed files, and solved it.

**Comment by Skack97** [comment] 2024-07-24 16:01
The fix is also broken for me since the game update. Crash to desktop on launch.

**Comment by Lyall** [comment] 2024-08-04 08:01
Not sure where these "updates" are coming from as the Steam version is still on v1.0.1. Unless we're talking about the MS Store version in which case I don't know what extra updates are out for that verison.

![image](https://github.com/user-attachments/assets/5adf7d22-ed4e-44b5-b71a-99ee78cb0d5c)

I'd suggest verifying game files on Steam and then re-installing SMTVFix.

**Comment by Crunchyroll001** [comment] 2024-08-06 18:39
i can verify that removing the fix entirely allowed my game to boot up,

**Comment by Skack97** [comment] 2024-08-06 19:36
I fixed mine by downloading the latest version of the mod through GitHub here, but whatever is uploaded to nexus currently is not working.

**Comment by Crunchyroll001** [comment] 2024-08-06 19:42
> I fixed mine by downloading the latest version of the mod through GitHub here, but whatever is uploaded to nexus currently is not working.

much appreciated, this fixed it for me!

**Comment by Lyall** [comment] 2024-08-08 14:05
The nexusmods version aren't uploaded by me so they are likely out-of-date. I should really post my own stuff there, but it's good to have all the issue reporting contained to GitHub.

**Comment by EspurrFan** [comment] 2024-08-08 22:33
I'm getting a crash on startup after installing the newest version, tried reinstalling the game and mod as well. Is there anything I can provide to assist in finding the cause of the crashing?

**Comment by Lyall** [comment] 2024-08-08 22:35
> I'm getting a crash on startup after installing the newest version, tried reinstalling the game and mod as well. Is there anything I can provide to assist in finding the cause of the crashing?

Can you post your `SMTVFix.log` file?

**Comment by EspurrFan** [comment] 2024-08-08 22:43
[SMTVFix.log](https://github.com/user-attachments/files/16553983/SMTVFix.log)
Here's my file

**Comment by peropero-github** [comment] 2024-08-09 07:15
0.9.3 is crashing on boot for me as well. Reverting to 0.9.2 currently works. 
Here's my 0.9.3 log file if it helps: [SMTVFix.log](https://github.com/user-attachments/files/16557424/SMTVFix.log)

**Comment by 0xH000000** [comment] 2024-08-09 11:19
Setting "Enable Console" to false fixed the issue for me.

**Comment by Lyall** [comment] 2024-08-09 18:55
> Setting "Enable Console" to false fixed the issue for me.

Can you confirm if the test build I linked in the prior post works for you?

**Comment by peropero-github** [comment] 2024-08-10 14:28
Can confirm the 0.9.4 test build is working for me, thanks!

**Comment by Lyall** [comment] 2024-08-10 22:37
Alright I've put out v0.9.4 which should fix potential crashing related to console construction. Since the main topic of this issues is related to an update that isn't out yet, I'm going to close this issue. If you run in to any crashing or other issues, feel free to create a new one.

**Closed by Lyall** 2024-08-10 22:37 UTC
